[package]
name = "hecs_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
derive_more = "0.99.17"
fxhash = "0.2.1"
log = "0.4.20"
